# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solenix < Formula
  desc "Lightweight time-series database with built-in UI"
  homepage "https://synthetis.tech"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/synthetis-tech/solenix/releases/download/v0.1.0/solenix_darwin_amd64.tar.gz"
      sha256 "ff01f2d7f51efc8c03a41407f8fe701124941ec46b05451b4c9de72413daee8d"

      define_method(:install) do
        bin.install "solenix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/synthetis-tech/solenix/releases/download/v0.1.0/solenix_darwin_arm64.tar.gz"
      sha256 "4e574b299abfc93e51cff61729e9425de981cbcf16d34893bbe9a1145ed17f5f"

      define_method(:install) do
        bin.install "solenix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/synthetis-tech/solenix/releases/download/v0.1.0/solenix_linux_amd64.tar.gz"
      sha256 "22883d87159c6bbbf9e217c2a9a77cb447c0c7788b1be86ab2b9ed4bf95197e4"
      define_method(:install) do
        bin.install "solenix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/synthetis-tech/solenix/releases/download/v0.1.0/solenix_linux_arm64.tar.gz"
      sha256 "f61c28de9a22d1735d47439c99ac5fd45d3997c8f718a0bf898fbdbeb7138350"
      define_method(:install) do
        bin.install "solenix"
      end
    end
  end

  test do
    system "#{bin}/solenix", "--version"
  end
end
