# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solenix < Formula
  desc "Lightweight time-series database with built-in UI"
  homepage "https://synthetis.tech"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/synthetis-tech/solenix/releases/download/v0.2.1/solenix_darwin_amd64.tar.gz"
      sha256 "2e0b45c5c7e949bf6d1309d28a58258c9e884964452dd11d6d72eec827ad6e0c"

      define_method(:install) do
        bin.install "solenix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/synthetis-tech/solenix/releases/download/v0.2.1/solenix_darwin_arm64.tar.gz"
      sha256 "e522ac1abd6a4169198c8b92a16e2b1c3131c048b9a44f6080263d4e0b28d307"

      define_method(:install) do
        bin.install "solenix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/synthetis-tech/solenix/releases/download/v0.2.1/solenix_linux_amd64.tar.gz"
      sha256 "1beff1de90bcb45039cda478720a1efefca59b6571b5e3f25bf385db02492ca7"
      define_method(:install) do
        bin.install "solenix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/synthetis-tech/solenix/releases/download/v0.2.1/solenix_linux_arm64.tar.gz"
      sha256 "0dc25b92038126902d230442eeb61e92c080ae5a9d81d2d10076e89db77fb209"
      define_method(:install) do
        bin.install "solenix"
      end
    end
  end

  test do
    system "#{bin}/solenix", "--version"
  end
end
